In [1]:
import numpy as np

BASIC ARRAY GENERATION


In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [4]:
a=[1,2,3,"hello","world"]
a

[1, 2, 3, 'hello', 'world']

In [5]:
np.array(a)


array(['1', '2', '3', 'hello', 'world'], dtype='<U21')

In [6]:




a=[1,2,3.4]
np.array(a)

array([1. , 2. , 3.4])

In [7]:
np.array([[1,2,3],[2,3,4],[3,4,5]])


array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
matrice=[[2,3],[3,4]]
matrice

[[2, 3], [3, 4]]

In [9]:
np.array(matrice)

array([[2, 3],
       [3, 4]])

ARRAY GENERATION FUNCTION

In [10]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
arr=np.ones((2,3))

In [13]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

linear space

In [14]:
arr=np.linspace(1,5,2)

In [15]:
arr

array([1., 5.])

In [16]:
arr=np.linspace(1,10,4)

In [17]:
arr

array([ 1.,  4.,  7., 10.])

In [18]:
arr=np.linspace(1,2,100)

In [19]:
arr

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

RANDOM GENERATION FUNCTION

NUMPY +RANDOM LIBRARY

In [20]:
np.random.rand(10)

array([0.42639209, 0.94402078, 0.30219787, 0.23145602, 0.98554872,
       0.62896201, 0.8913175 , 0.01088766, 0.51800977, 0.98765018])

normalisation- no. between 0-1


In [21]:
np.random.randn(10)

array([ 0.72742011,  1.71905586, -0.05499985, -0.01975218, -0.19330773,
        0.41233078,  2.35145896, -1.02094639,  0.8345035 , -0.61625817])

standardisation-number netwen -3 to 3

In [22]:
np.random.randint(3)

1

In [23]:
np.random.randint(10,20,8)

array([11, 16, 13, 10, 15, 12, 17, 15])

array attributes

In [24]:
arr=np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7]])
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [25]:
arr.shape

(3, 4)

In [26]:
arr.size

12

In [27]:
arr.dtype

dtype('int64')

ARRAY. METHODS

In [28]:
arr.min()

np.int64(1)

In [29]:
arr.max()

np.int64(7)

In [30]:
arr.sum()

np.int64(46)

In [31]:
arr=np.array([[2,2,3,4],[2,3,4,5],[4,5,6,7],[2,4,5,6]])
arr

array([[2, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7],
       [2, 4, 5, 6]])

In [32]:
arr.min()

np.int64(2)

In [33]:
arr.max()

np.int64(7)

In [34]:
arr.sum()

np.int64(64)

In [35]:
np.sum(arr,axis=0)

array([10, 14, 18, 22])

In [36]:
np.sum(arr,axis=1)

array([11, 14, 22, 17])

In [37]:
arr.mean()

np.float64(4.0)

In [38]:
arr.std()

np.float64(1.541103500742244)

In [39]:
arr.argmax()

np.int64(11)

In [40]:
arr.argmin()

np.int64(0)

reshaping and resizing

In [41]:
arr=np.arange(1,31)

In [42]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr=arr.reshape(6,5)

In [44]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [45]:
arr=np.array([[1,2,3],[1,2,4],[2,3,4],[2,4,5]])
print(arr.ndim)

2


In [46]:
np.sum(arr,axis=1)

array([ 6,  7,  9, 11])

numopy indexing and slicing


In [47]:
arr=np.arange(11,21)

In [48]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr[3::2]

array([14, 16, 18, 20])

In [50]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

indexing and slicing of matrix

In [51]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [52]:
arr[5]

array([26, 27, 28, 29, 30])

In [53]:
arr[5,4]

np.int64(30)

In [54]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [55]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [56]:
arr[3:,3:]




array([[19, 20],
       [24, 25],
       [29, 30]])

boolean indexing

In [57]:
arr=np.arange(11,21)

In [58]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
bool_index=arr%2!=0

In [60]:
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [61]:
arr=arr[bool_index]

In [62]:
arr

array([11, 13, 15, 17, 19])