### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[50, 84, 31, 92],
       [ 9, 99, 32, 95],
       [67, 40, 41, 98],
       [68,  4, 48, 17],
       [52, 46, 70, 55],
       [72, 68, 48, 38]])

In [5]:
np.sort(a)[::-1]

array([90, 88, 87, 75, 66, 65, 64, 52, 47, 47, 43, 33, 31, 22,  4])

In [6]:
np.sort(a)[::-1]

array([90, 88, 87, 75, 66, 65, 64, 52, 47, 47, 43, 33, 31, 22,  4])

In [7]:
np.sort(b,axis=0)

array([[ 9,  4, 31, 17],
       [50, 40, 32, 38],
       [52, 46, 41, 55],
       [67, 68, 48, 92],
       [68, 84, 48, 95],
       [72, 99, 70, 98]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 31,  66,  33,  52,   4,  43,  47,  47,  87,  22,  88,  75,  64,
        90,  65, 200])

In [10]:
b

array([[50, 84, 31, 92],
       [ 9, 99, 32, 95],
       [67, 40, 41, 98],
       [68,  4, 48, 17],
       [52, 46, 70, 55],
       [72, 68, 48, 38]])

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[50., 84., 31., 92.,  1.],
       [ 9., 99., 32., 95.,  1.],
       [67., 40., 41., 98.,  1.],
       [68.,  4., 48., 17.,  1.],
       [52., 46., 70., 55.,  1.],
       [72., 68., 48., 38.,  1.]])

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[50.        , 84.        , 31.        , 92.        ,  0.60974624],
       [ 9.        , 99.        , 32.        , 95.        ,  0.7093632 ],
       [67.        , 40.        , 41.        , 98.        ,  0.3964948 ],
       [68.        ,  4.        , 48.        , 17.        ,  0.4674952 ],
       [52.        , 46.        , 70.        , 55.        ,  0.64595116],
       [72.        , 68.        , 48.        , 38.        ,  0.30400635]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [17]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [21]:
np.expand_dims(a,axis=1)

array([[31],
       [66],
       [33],
       [52],
       [ 4],
       [43],
       [47],
       [47],
       [87],
       [22],
       [88],
       [75],
       [64],
       [90],
       [65]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [23]:
a>50

array([False,  True, False,  True, False, False, False, False,  True,
       False,  True,  True,  True,  True,  True])

In [26]:
a[a>50]

array([66, 52, 87, 88, 75, 64, 90, 65])

In [27]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  8, 10, 11, 12, 13, 14]),)

In [30]:
# replace all values > 50 with 0
np.where(a>50,0,1)

array([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([31,  0, 33,  0,  4, 43, 47, 47,  0, 22,  0,  0,  0,  0,  0])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [32]:
# code
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [33]:
np.argmax(a)

np.int64(13)

In [34]:
b

array([[50, 84, 31, 92],
       [ 9, 99, 32, 95],
       [67, 40, 41, 98],
       [68,  4, 48, 17],
       [52, 46, 70, 55],
       [72, 68, 48, 38]])

In [35]:
np.argmax(b,axis=0)

array([5, 1, 4, 2])

In [36]:
np.argmax(b,axis=1)

array([3, 1, 3, 0, 2, 0])

In [37]:
# np.argmin
np.argmin(a)

np.int64(4)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [38]:
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [39]:
np.cumsum(a)

array([ 31,  97, 130, 182, 186, 229, 276, 323, 410, 432, 520, 595, 659,
       749, 814])

In [40]:
b

array([[50, 84, 31, 92],
       [ 9, 99, 32, 95],
       [67, 40, 41, 98],
       [68,  4, 48, 17],
       [52, 46, 70, 55],
       [72, 68, 48, 38]])

In [41]:
np.cumsum(b,axis=1)

array([[ 50, 134, 165, 257],
       [  9, 108, 140, 235],
       [ 67, 107, 148, 246],
       [ 68,  72, 120, 137],
       [ 52,  98, 168, 223],
       [ 72, 140, 188, 226]])

In [46]:
np.cumsum(b,axis=0)

array([[ 50,  84,  31,  92],
       [ 59, 183,  63, 187],
       [126, 223, 104, 285],
       [194, 227, 152, 302],
       [246, 273, 222, 357],
       [318, 341, 270, 395]])

In [42]:
np.cumsum(b)

array([  50,  134,  165,  257,  266,  365,  397,  492,  559,  599,  640,
        738,  806,  810,  858,  875,  927,  973, 1043, 1098, 1170, 1238,
       1286, 1324])

In [43]:
# np.cumprod
np.cumprod(a)

array([                  31,                 2046,                67518,
                    3510936,             14043744,            603880992,
                28382406624,        1333973111328,      116055660685536,
           2553224535081792,   224683759087197696, -1595462142169724416,
        8570887343394947072, -3383390190255931392,  1440566517879078912])

In [44]:
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [50]:
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [51]:
np.percentile(a,50)

np.float64(52.0)

In [52]:
np.median(a)

np.float64(52.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [53]:
# code
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [55]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 0, 1, 2, 3, 1, 3, 1, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [56]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [57]:
# code
a


array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [58]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [59]:
# code
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [60]:
np.flip(a)

array([65, 90, 64, 75, 88, 22, 87, 47, 47, 43,  4, 52, 33, 66, 31])

In [61]:
b

array([[50, 84, 31, 92],
       [ 9, 99, 32, 95],
       [67, 40, 41, 98],
       [68,  4, 48, 17],
       [52, 46, 70, 55],
       [72, 68, 48, 38]])

In [62]:
np.flip(b,axis=1)

array([[92, 31, 84, 50],
       [95, 32, 99,  9],
       [98, 41, 40, 67],
       [17, 48,  4, 68],
       [55, 70, 46, 52],
       [38, 48, 68, 72]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [63]:
# code
a

array([31, 66, 33, 52,  4, 43, 47, 47, 87, 22, 88, 75, 64, 90, 65])

In [65]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  33,  52,   4,  43,  47,  47,  87,  22,  88,  75,  64,
        90,  65])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [66]:

# code
a

array([110, 530,  33,  52,   4,  43,  47,  47,  87,  22,  88,  75,  64,
        90,  65])

In [67]:
np.delete(a,[0,2,4])

array([530,  52,  43,  47,  47,  87,  22,  88,  75,  64,  90,  65])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [68]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
np.intersect1d(m,n)

array([3, 4, 5])

In [70]:
np.setdiff1d(n,m)

array([6, 7])

In [71]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [73]:
m[np.in1d(m,1)]

/tmp/ipykernel_1001/524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals